
import React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Providers } from "./provider"
import { ReduxProviders } from "@/redux"
import { ThemeProvider } from "next-themes"
import { Modals } from "@/components/modals"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider attribute="class" defaultTheme="dark">
                    <ReduxProviders> 
                        <Providers>
                            {children}
                            <Modals/>
                        </Providers>
                    </ReduxProviders>
                </ThemeProvider>
            </body>
        </html>
    )
}
